### ISSUE TITLE
Grafana Plugin CrateDB deprecated

### ISSUE THREAD

**Issue by tstorek** [Fiware/tutorials.Time-Series-Data#19]
Hello,

Thanks, for all this brilliant tutorials. However, as far as I know the crateDB plugin for grafana is longer listed as official plugin. Hence, this should be updated according to [https://github.com/smartsdk/ngsi-timeseries-api/issues/166](https://github.com/smartsdk/ngsi-timeseries-api/issues/166)  

Thanks,

Thomas

**Comment by jason-fox** [comment]
@taliaga - what do you think? Does this tutorial need to switch to use PostGres when it is updated for the `0.6.1` release?

**Comment by taliaga** [comment]
thanks for the heads-up, I'll that this in this tutorial

**Comment by jason-fox** [comment]
@taliaga - I have updated the YAML config whilst fixing another issue, the latest version successfully persists data into Crate-DB 3.1.2 - 7804e00

However I have not had time to check or amend the *Grafana* section -could you check and amend as necessary.
