### ISSUE TITLE
Postman collection outdated - location queries not working

### ISSUE THREAD

**Issue by rsisto** [Fiware/tutorials.Time-Series-Data#28]
Using the postman collection suggested works for almost everything, but the location queries at the end (and Grafana dashboard for location) are not working.

Furthermore, I tried changing request nr.2 to add location attribute as notification, but the request Nr 10 ( LATEST N SAMPLED VALUES OF DEVICES NEAR A POINT) won't bring any data.

Thanks for your comments!

**Comment by jason-fox** [comment]
Looks like the additional `location` attribute added during device provisioning has been deleted when standardizing the device-provisioning scripts. Please try again.

I mean you can't look for latest values **near to** a point if you don't supply a point can you :smile:

**Comment by rsisto** [comment]
Hey Jason, great timing! :)

I cloned the repo again and everything works now, I suspected something like that but didn't want to guess, thanks!

Just for the sake of the next tutorial follower... the only issue now is the link to the postman collection. It's still missing the location attribute in the "Orion - QuantumLeap - Sample Lamp Luminosity" request.
