### ISSUE TITLE
Review FIWARE ports

### ISSUE THREAD

**Issue by helderjordao-dtx** [Fiware/tutorials.Time-Series-Data#36]
At the example there is some incoherence, because in some parts the documentation talks about the port 8668 and at the architecture design it appears 8868.

I tried to run the tutorial but the CrateDB doesn't start it (this should be reason to open other issue)

**Comment by jason-fox** [comment]
Is this a placeholder for a real issue or was it raised in error and can it be closed?

**Comment by jason-fox** [comment]
4848af4 and 5db2ce5 have updated the text.  Can this documentation issue be closed now?

If Crate-DB is failing to start, please ensure you have the latest images by running:

```console
./services create
```

This will pull the latest SemVer versions of the various images which should work nicely together - I think the supported Crate version may have changed with a recent release of QuantumLeap. If it still doesn't work, please raise the Crate issue separately and keep this one for the documentation changes.

**Comment by helderjordao-dtx** [comment]
ok, thanks for your comment, I will try other Create DB version and then I comment here.
If you want you can close the issue.
