### ISSUE TITLE
IoT Agent blocked by CORS policy

### ISSUE THREAD

**Issue by johncaipa** [Fiware/tutorials.Time-Series-Data#45]
Hi, I am trying to GET information about the services and devices provided from an application in nodejs, and I get the following error messages, they work from postman, could you tell me what the problem could be, or how should I enable CORS in the IoT Agent? thanks
![WhatsApp Image 2022-04-11 at 7 25 38 PM](https://user-images.githubusercontent.com/31298276/162856299-4e7247c3-4231-449a-a2d4-6743c61959b8.jpeg)
I don't know if I'm doing something wrong, I didn't find information about it in the documentation

**Comment by jason-fox** [comment]
I know [Orion](https://github.com/telefonicaid/fiware-orion) supports CORS, but don't know if the [IoT Agent node lib](https://github.com/telefonicaid/iotagent-node-lib) does. You would be better off asking a question to the developers on GitHub over on their repo.  You may need to use a local [CORS proxy](https://github.com/garmeeh/local-cors-proxy) to bypass the issue.

**Comment by jason-fox** [comment]
Closing as this issue is not directly relevant to the tutorial.
