### ISSUE TITLE
Error in WLS environment

### ISSUE THREAD

**Issue by drypatrick** [Fiware/tutorials.Time-Series-Data#48]
Running the services script in WLS, leads to some errors, which seams related to the syntax:
`': not a valid identifier export: ``
I've solved running [dos2unix](https://dos2unix.sourceforge.io/) on:
- services
- .env

Maybe these files have been created/edit on Windows, who have different line endings?

On other tutorial repositories, I haven't found the same problems.

**Comment by jason-fox** [comment]
I couldn't find any issue with `services`. I have updated `.env`  here -  2c9a11a . Strange that the line-ending was incorrect since it wasn't created in Windows anyway. Could you check if the change is sufficient for you?

**Comment by drypatrick** [comment]
Now it works like any other tutorial.
